// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANtMIMvFdCFF2A31xFPNjeb8tlmEvQvTM',
    appId: '1:748168691116:web:5b590afda994eadd910e09',
    messagingSenderId: '748168691116',
    projectId: 'nothing---ecommerce-app',
    authDomain: 'nothing---ecommerce-app.firebaseapp.com',
    storageBucket: 'nothing---ecommerce-app.appspot.com',
    measurementId: 'G-1E5XYXQ027',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIZJKCF_FCQfZG3j8o2eCkNP0mnrht6yo',
    appId: '1:748168691116:android:5498c80bed33459c910e09',
    messagingSenderId: '748168691116',
    projectId: 'nothing---ecommerce-app',
    storageBucket: 'nothing---ecommerce-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4uMc1LRWmtQ0WkIKVw_5lggIjEvIwy98',
    appId: '1:748168691116:ios:714572cd679b6c6a910e09',
    messagingSenderId: '748168691116',
    projectId: 'nothing---ecommerce-app',
    storageBucket: 'nothing---ecommerce-app.appspot.com',
    iosClientId: '748168691116-f1i7l2cnjrfvo1mfvgj6nk0aefq4di3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4uMc1LRWmtQ0WkIKVw_5lggIjEvIwy98',
    appId: '1:748168691116:ios:714572cd679b6c6a910e09',
    messagingSenderId: '748168691116',
    projectId: 'nothing---ecommerce-app',
    storageBucket: 'nothing---ecommerce-app.appspot.com',
    iosClientId: '748168691116-f1i7l2cnjrfvo1mfvgj6nk0aefq4di3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
